### ISSUE TITLE
"Dark mode" switch doesn't work

### ISSUE THREAD

**Issue by cboltz** [openSUSE/chameleon#11]
The "Dark mode" switch on en-test.opensuse.org doesn't work anymore. I know that it worked in the past, but I don't know when it broke.

I tested with Firefox 70.0.1 and Chromium 78, both running on latest Tumbleweed.

**Comment by guoyunhe** [comment]
Here is a jQuery error, which is from another component. I need to fix that, then the dark mode switch should work.

**Comment by cboltz** [comment]
Fixed by PR 52 :-) - thanks!
