### ISSUE TITLE
Wrong text color in tables with enabled dark mode

### ISSUE THREAD

**Issue by EGD** [openSUSE/chameleon#12]
source in [en.oo wiki](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Detect_a_distribution_flavor_for_special_code)
![Screenshot_20200105_160933](https://user-images.githubusercontent.com/720688/71780641-36f8c000-2fd6-11ea-9774-25492af8a96a.png)

**Comment by guoyunhe** [comment]
Should be fixed. Ctrl+F5 to refresh.
