### ISSUE TITLE
can't use chamelon theme in own app

### ISSUE THREAD

**Issue by lnussel** [openSUSE/chameleon#14]
I've written a small app using jquery and bootstrap and wanted to switch to openSUSE's theme. However, including chameleon doesn't work:

* Request to access cookie or storage on “https://static.opensuse.org/chameleon/dist/js/chameleon-no-bootstrap.js” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
foobar.suse.de:5000
* Error: Closing client. Could not access localStorage in hub. 2 chameleon-no-bootstrap.js:1:64111
* Request to access cookie or storage on “https://static.opensuse.org/chameleon/hub.html” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

Looking at https://bootswatch.com/ it seems it's possible to have a bootstrap theme with only a css. Would it be possible to have a variant of chameleon that only replaces the css? Ie to only get the colors and styling but not extra controls?

**Comment by guoyunhe** [comment]
Hi, so the issue is related to Cookies/localStorage/CrossStorage. I think I can simply add a flag to disable all these things. All these storage accesses are actually for only one feature: the dark/light mode switching. If we disable the switch, the issue can also be fixed.

**Comment by guoyunhe** [comment]
I removed all cookies/localStorage/CrossStorage related code. Should be okay now.

**Comment by lnussel** [comment]
Works better now, thanks! I still get this though:

* Request to access cookie or storage on “https://static.opensuse.org/chameleon/dist/css/chameleon.css” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
foobar.suse.de:5000
* Request to access cookie or storage on “https://static.opensuse.org/chameleon/dist/js/chameleon-no-bootstrap.js” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

Do I actually need the js btw or is the css enough?

**Comment by guoyunhe** [comment]
I think your app configuration doesn't allow any external resources. So even CSS linking is blocked.

So I suggest to not use static.opensuse.org . Just download the repo, copy things ender `dist` folder into your app. Link `chameleon.css` and `chameleon-no-bootstrap.js` from there.

**Comment by lnussel** [comment]
ic. closing then. Thanks!
