### ISSUE TITLE
Don't build wiki into the main stylesheet/js

### ISSUE THREAD

**Issue by hellcp** [openSUSE/chameleon#16]
The stylesheet and js get a little bit bloated, and add classes that might conflict with other software, it would be good to only build in wiki stylesheet for wikis.

**Comment by guoyunhe** [comment]
Wiki contains a lot of bento styles. So we added some SaSS extends magic to override them. This part can be do in other way: replace class names with JS.

JS part can be built separately for sure.

**Comment by hellcp** [comment]
I don't think the fact that sass for it exists is a problem, the problem is that no other website should and hopefully will never use those styles, so they should not exist in a common stylesheet

**Comment by guoyunhe** [comment]
Rely on https://github.com/openSUSE/wiki/pull/54

**Comment by guoyunhe** [comment]
This has been fixed in `dev` branch. Will deploy to static.opensuse.org when heroes have time.
