### ISSUE TITLE
Branching model change

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/chameleon#18]
1. [x] A new branch `dev` will be created.
2. [x] New commits can only go to `dev` branch. No direct commit to `master`.
3. [x] New release, like the following v2.0.0, will be merged from `dev` to `master`.
4. [x] Each release has a branch, like rel-1.3. We will deploy it at `/chameleon-1.3`. We only push critical bug fixes to release branches. No feature or design changes.
5. [ ] In CDN static.opensuse.org, we will have another version `/chameleon-dev`. only for live testing.
6. [ ] Write down a list of sites for testing and instructions. Only when all tests passed, a `dev` version can be merged into `master`.

@hellcp

**Comment by hellcp** [comment]
If you want, we can publish [releases](https://github.com/openSUSE/chameleon/releases) as directories on the static server, that would allow to reference older versions of the theme and allow the maintainer of the app to update in their free time

**Comment by guoyunhe** [comment]
I am not sure how the cron jobs is working in static.opensuse.org. If they do `git submodule update --init` every hour, then we just need to add the release as a submodule of https://github.com/openSUSE/static.opensuse.org

**Comment by guoyunhe** [comment]
1. Released version `v2.0.0`.
2. Created branch `rel-2.0`.
3. `rel-2.0` will be hosted at https://static.opensuse.org/chameleon-2.0/ (waiting for heroes to merge and deploy)
4. `rel-2.0` will never be updated unless people report critical bugs that cannot wait for next release.
5. Site maintainers can upgrade to `rel-2.1` whenever they want.

**Comment by hellcp** [comment]
Sounds good to me, I would reserve 2.0.1 for bugfixes, because it's easy enough to change a number on one site, and bugs can still be used on some sites (I know I ~~ab~~use some bugs), otherwise sounds sane

**Comment by guoyunhe** [comment]
@hellcp it may take several weeks to get the CDN deployed. Before that I won't push anything to master. Only dev branch will be updated.

**Comment by hellcp** [comment]
excellent, thank you

**Comment by guoyunhe** [comment]
@hellcp now you can switch from:
```
static.opensuse.org/chameleon/
```
to
```
static.opensuse.org/chameleon-2.0/
```
master branch will not be touched until all sites have been switched to versioned URLs.

all new changes will happen in dev branch. and I am preparing for 3.0.
