### ISSUE TITLE
Icon alignment issues

### ISSUE THREAD

**Issue by hellcp** [openSUSE/chameleon#29]
3.0 has awful alignment issues with icons, all of them are slightly lower than the text baseline
Current:
![](https://user-images.githubusercontent.com/30577011/84808304-cdf78880-b008-11ea-9659-47d3e1872c6d.png)
Proper alignment:
![](https://user-images.githubusercontent.com/30577011/84808308-cf28b580-b008-11ea-804b-1d1db58e250b.png)

This applies to pretty much every icon, navbar icons, search icon, megamenu button icon, and, as seen on the screenshot, megamenu itself

**Comment by hellcp** [comment]
Maybe as a sidenote could we have some additional space next to the openSUSE button in the navbar? `mr-1` looks about right

**Comment by guoyunhe** [comment]
Can you check it again?

![image](https://user-images.githubusercontent.com/5836790/84815320-875f5980-b01b-11ea-9113-8ec0ec332540.png)

**Comment by hellcp** [comment]
Yup, that's perfect, thanks!
