### ISSUE TITLE
GitHub pages

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/chameleon#6]
Hi @lnussel , I want to enable GitHub pages feature for the repository. But I don't have permission to do it. Can you help?

And one more thing, the name of the repository is too long, which will make the URL of GitHub pages this long https://opensuse.github.io/opensuse-theme-chameleon/ can we rename it to chameleon?

**Comment by lnussel** [comment]
I made you maintainer

**Comment by guoyunhe** [comment]
Thanks!

**Comment by guoyunhe** [comment]
@lnussel I found that maintainer doesn't have permission to enable GitHub pages... Maybe it is restricted to owners.

**Comment by guoyunhe** [comment]
GitHub Pages has been published. But still cannot rename the repo.

**Comment by lnussel** [comment]
changed the permissison level to Admin, maybe that helps

**Comment by guoyunhe** [comment]
Yes, it worked. Thanks!
