### ISSUE TITLE
Icon set

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/chameleon#7]
I am thinking to replace Typicon. Its amount of icons is too small. It is not maintained and a bit out-dated.

The icon set from EOS design system is based on Material Design Icons, which I don't like... Material Design is the identity of Google and Android. We have nothing to do with either of them.

Creating our own icon set and guideline seems a big project. But I guess we won't need too many icons. So let's try!

**Comment by guoyunhe** [comment]
@hellcp I found a neutral looking icon set https://github.com/Remix-Design/remixicon

1. It doesn't look like Google/Apple/Microsoft branding.
2. It is something between KDE Breeze and GNOME icons, won't be too outstanding in any DE.
3. The style is very simple, mostly straight lines, so we can easily extends it with openSUSE specific icons.
4. The team is very active and adds icons regularly.

Do you think we can extend the icon set to make a chameleon icon set?

**Comment by hellcp** [comment]
sure

**Comment by guoyunhe** [comment]
Now using extended Remix Icon.
