### ISSUE TITLE
Ship a set of favicons

### ISSUE THREAD

**Issue by hellcp** [openSUSE/chameleon#8]
It would be great to ship a set of favicons like https://github.com/openSUSE/news-o-o/tree/master/assets/favicons, so we don't have to ship them for every project

**Comment by guoyunhe** [comment]
Yes, and here was a ticket about unifying all favicons in all openSUSE sites. Now they all are using different icons.

In case we change the favicons in future, have an CDN (static.opensuse.org) for favicons is the best solution. Just need to replace one file, then all sites get updated.

chameleon is also hosted in static.opensuse.org as a sub directory. We can either ship favicon in static.o.o repo, or in chameleon repo.

artwork repo already contains some icons/logos. If we host it in static.opensuse.org, favicons can be included there, too. Chameleon is still more about CSS/JS. Icons are mostly copied from artwork repo. (Is here any way that we can reduce the size of artwork repo? I cannot even clone it last time...)

**Comment by hellcp** [comment]
In the past this was done with https://opensuse.org/favicon.ico, but due to some issues with deployment, we cannot currently change it (and it is the SUSE geeko), so shipping it together with chameleon so it gets deployed on static seems like the best option.

**Comment by guoyunhe** [comment]
Then let's ship it here. Do we already have a selection of favion?

**Comment by hellcp** [comment]
Yeah, the ones from news-o-o folder I sent should be good to go

**Comment by guoyunhe** [comment]
Can you make a PR?

Once it is merged (after 1 hour synchronization cycle), it will be available at URL `https://static.opensuse.org/chameleon/dist/favicons/xxx.xxx`.
